Ote/fta
kieler/stpa pull request #11
Opened 2023-07-04 11:27 UTC by OrhanTekin

2023-07-06 14:18 UTC, Drakae requested changes
Additionally to the comments, please merge the master into your branch.

2023-07-06 14:18 UTC, Drakae commented on extension/src/language-extension.ts
> +                cutSetDropDownList.push({id: id, value: set});
Why do you need an ID in addition to the value?

2023-07-06 14:18 UTC, Drakae commented on extension/src/wview.ts
> +
not needed

2023-07-06 14:18 UTC, Drakae commented on extension/src-webview/options/cut-set-registry.ts
> +            this.highlightSelectedNodes(this.selectedCutSet);
not needed. Instead inject the registry in the "fta-views" file and ask for the value of the dropdown menu. Then you can highlight there the nodes and edges you want to highlight.

2023-07-06 14:18 UTC, Drakae commented on extension/src-webview/views.tsx
> +        setFTANodesAndEdges(allNodes, model.children as SEdge[]);
not needed

2023-10-10 10:27 UTC, Eddykasp commented on extension/package.json
> +                    "when": "editorLangId == 'stpa' || editorLangId == 'fta'"
see https://github.com/kieler/kieler-vscode/pull/75

2023-10-10 10:27 UTC, Eddykasp commented on extension/src-language-server/fta/analysis/fta-cutSet-calculator.ts
> +    if (isAND(startNode) || isInhibitGate(startNode)) {
this if(isA)... else if(isB) etc.. structure could be replaced by a switch case to be more readable I think

2023-10-10 10:27 UTC, Eddykasp commented on extension/src-language-server/fta/diagram/fta-layout-config.ts
> +    protected graphOptions(sgraph: SGraph, index: SModelIndex): LayoutOptions {
sgraph, index unused vars

2023-10-10 10:27 UTC, Eddykasp commented on extension/src-language-server/fta/diagram/fta-layout-config.ts
> +    protected nodeOptions(snode: SNode, index: SModelIndex): LayoutOptions | undefined {
snode, index unused vars

2023-10-10 10:27 UTC, Eddykasp commented on extension/src-webview/fta/fta-views.tsx
> +            const p = segments[i];
what is a p?

2023-10-10 10:27 UTC, Eddykasp commented on extension/src-webview/options/render-options-registry.ts
> +
remove whitespace

2023-10-10 10:27 UTC, Eddykasp commented on extension/src-webview/options/render-options-registry.ts
> +        }
remove whitespace

2023-10-10 10:27 UTC, Eddykasp commented on extension/src-webview/views-rendering.tsx
> +    const d = `M ${leftX}, ${midY} V ${botY} H ${rightX} V ${midY} C ${rightX}, ${midY} ${rightX}, ${topY} ${midX}, ${topY} ${leftX}, ${topY} ${leftX}, ${midY} ${leftX}, ${midY} Z`;
what is a d?

2023-10-10 10:27 UTC, Eddykasp commented on extension/src-webview/views-rendering.tsx
> +    // 'M' + leftX + " " + midY + " V " + botY + " H " + rightX + " V " + midY + " C " + rightX + " " + midY + " " + rightX + " "
is this comment helpful?

2023-10-10 10:27 UTC, Eddykasp commented on extension/src-webview/views-rendering.tsx
> +    const d = `M${leftX},${midY} V ${botY}` + `C ${leftX}, ${botY} ${leftX+10}, ${nearBotY} ${midX}, ${nearBotY} ${rightX-10}, ${nearBotY} ${rightX}, ${botY} ${rightX}, ${botY}`
see above

2023-10-10 10:27 UTC, Eddykasp commented on extension/src-webview/views-rendering.tsx
> +    const d = `M${leftX},${midY} V ${botY}` + `C ${leftX}, ${botY} ${leftX+10}, ${nearBotY} ${midX}, ${nearBotY} ${rightX-10}, ${nearBotY} ${rightX}, ${botY} ${rightX}, ${botY}`
see above, all these constructions are quite obscure, maybe a comment explaining what shape is being made would be helpful

2023-10-10 10:27 UTC, Eddykasp commented on extension/src-webview/views-rendering.tsx
> +    const d = 'M' + leftX + " " + lowY + " L " + leftX + " " + highY + " L " + midX + " " + highestY + " L " + rightX
this is done differently than the previous ones

2023-10-10 10:27 UTC, Eddykasp commented on extension/src/language-extension.ts
> +        // TODO: ID enforcer for FTA
still todo?

2023-10-13 12:47 UTC, Drakae approved these changes

2023-10-13 12:50 UTC, merged